version: '3.8'

services:
  analyst-service:
    build: .
    command: /bin/bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    ports:
      - "8003:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    networks:

      - my_network
      - microservices-network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - my_network

networks:
  microservices-network:
    external: true
  my_network:

